plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	maven { url = "https://masa.dy.fi/maven/sakura-ryoko" }
	maven { url = "https://api.modrinth.com/maven" }
	maven { url = 'https://maven.fallenbreath.me/releases' }
}

loom {
	runs {
		client {
			client()
			configName = "Minecraft Client"
			ideConfigGenerated = true
			runDir = "run"
		}
	}
	// This creates the 'client' sourceSet and separates it from 'main'
	splitEnvironmentSourceSets()
}

// When using splitEnvironmentSourceSets, Loom uses 'processClientResources'
// for the client source set. We configure it here.
tasks.named('processClientResources', ProcessResources) {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}

	// Ensure we handle potential duplicates if Gradle tries to look in 'main'
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Disable the default processResources if you have no 'main' folder
// to prevent errors or empty folder creation
processResources {
	enabled = false
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version}:${project.malilib_version}"
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	// Crucial: Tell the JAR to package the 'client' output since 'main' is empty
	from sourceSets.client.output

	inputs.property "projectName", project.name
	from("LICENSE") {
		rename { "${it}_${project.name}"}
	}

	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
}