# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, workflow_dispatch]

env:
  MINECRAFT_VERSION: 1.21.11
  JAVA_VERSION: 25
  VERSION: 1.1.0+1.21.11
  RELEASE_NAME: Tsrheang Xray 1.1.0 for Minecraft 1.21.11
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN_2036 }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: MC Mod Space
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew clean build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1536287
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: y4K9OxC4
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
